djobs/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth.views import login, logout
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns(('djobs.views'),
    # Examples:
    # url(r'^$', 'djobs.views.home', name='home'),
    # url(r'^djobs/', include('djobs.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
)

urlpatterns += patterns((''),
    (r'^simpleblog/', include('simpleblog.urls')),
)

urlpatterns += patterns((''),
    #静态文件
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_PATH}
            # {'document_root': '/home/gs/djobs/static/'}
    ),
)

simpleblog/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import *


urlpatterns = patterns(('simpleblog.views'),
    url(r'^bloglist/$', 'blog_list', name='bloglist'),
    url(r'^blog/tag/(?P<id>\d+)/$', 'blog_filter', name='filtrblog'),
    url(r'^blog/search/$', 'blog_search', name='searchblog'),
    url(r'^blog/(?P<id>\d+)/$', 'blog_show', name='detailblog'),
    url(r'^blog/(?P<id>\w+)/del/$', 'blog_del', name='delblog'),
    url(r'^blog/(?P<id>\w+)/update/$', 'blog_update', name='updateblog'),
    url(r'^blog/add/$', 'blog_add', name='addblog'),
    url(r'^blog/addmassage/$', 'add_weibo', name='addmassage'),
    url(r'^blog/showweibo/$', 'show_weibo', name='showweibo'),
    url(r'^blog/(?P<id>\d+)/commentshow/$', 'blog_show_comment', name='showcomment'),
)

simpleblog/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models


class Tag(models.Model):
    """docstring for Tags"""
    tag_name = models.CharField(max_length=20)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.tag_name


class Author(models.Model):
    """docstring for Author"""
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)


class BlogManager(models.Manager):
    """docstring for BlogManager"""
    def title_count(self, keyword):
        return self.filter(caption__icontains=keyword).count()

    def tag_count(self, keyword):
        return self.filter(tags__icontains=keyword).count()

    def author_count(self, keyword):
        return self.filter(author__icontains=keyword).count()


class Blog(models.Model):
    """docstring for Blogs"""
    caption = models.CharField(max_length=50)
    author = models.ForeignKey(Author)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    count_objects = BlogManager()
    taglist = []

    def save(self, *args, **kwargs):
        super(Blog, self).save()
        for i in self.taglist:
            p, created = Tag.objects.get_or_create(tag_name=i)
            self.tags.add(p)

    def __unicode__(self):
        return u'%s %s %s' % (self.caption, self.author, self.publish_time)


class Weibo(models.Model):
    massage = models.CharField(max_length=200)
    author = models.ForeignKey(Author)
    publish_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.massage

simpleblog/forms.py
from django import forms


class BlogForm(forms.Form):
    """docstring for BlogForm"""
    caption = forms.CharField(label='title', max_length=100)
    content = forms.CharField(widget=forms.Textarea)


class TagForm(forms.Form):
    """docstring for TagForm"""
    tag_name = forms.CharField()


class WeiboForm(forms.Form):
    """docstring for WeiboForm"""
    massage = forms.CharField(widget=forms.Textarea)

simpleblog/views.py
from django.shortcuts import render_to_response
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import RequestContext
# from django.views.decorators.csrf import csrf_protect
from django.core.context_processors import csrf
from simpleblog.forms import BlogForm
from simpleblog.forms import TagForm
from simpleblog.models import Blog
from simpleblog.models import Author
from simpleblog.models import Tag
from simpleblog.models import Weibo


def blog_list(request):
    blogs = Blog.objects.order_by('-id')
    tags = Tag.objects.all()
    weibos = Weibo.objects.order_by('-publish_time')[:5]
    return render_to_response("blog_list.html",
        {"blogs": blogs, "tags": tags, "weibos": weibos},
        context_instance=RequestContext(request))


def blog_filter(request, id=''):
    tags = Tag.objects.all()
    tag = Tag.objects.get(id=id)
    blogs = tag.blog_set.all()
    return render_to_response("blog_filter.html",
        {"blogs": blogs, "tag": tag, "tags": tags})


def blog_search(request):
    tags = Tag.objects.all()
    if 'search' in request.GET:
        search = request.GET['search']
        blogs = Blog.objects.filter(caption__icontains=search)
        return render_to_response('blog_filter.html',
            {"blogs": blogs, "tags": tags}, context_instance=RequestContext(request))
    else:
        blogs = Blog.objects.order_by('-id')
        return render_to_response("blog_list.html", {"blogs": blogs, "tags": tags},
            context_instance=RequestContext(request))


def blog_show(request, id=''):
    try:
        blog = Blog.objects.get(id=id)
        tags = Tag.objects.all()
    except Blog.DoesNotExist:
        raise Http404
    return render_to_response("blog_show.html",
        {"blog": blog, "tags": tags},
        context_instance=RequestContext(request))


def blog_show_comment(request, id=''):
    blog = Blog.objects.get(id=id)
    return render_to_response('blog_comments_show.html', {"blog": blog})


def blog_del(request, id=""):
    try:
        blog = Blog.objects.get(id=id)
    except Exception:
        raise Http404
    if blog:
        blog.delete()
        return HttpResponseRedirect("/simpleblog/bloglist/")
    blogs = Blog.objects.all()
    return render_to_response("blog_list.html", {"blogs": blogs})


def blog_add(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        tag = TagForm(request.POST)
        if form.is_valid() and tag.is_valid():
            cd = form.cleaned_data
            cdtag = tag.cleaned_data
            tagname = cdtag['tag_name']
            for taglist in tagname.split():
                Tag.objects.get_or_create(tag_name=taglist.strip())
            title = cd['caption']
            author = Author.objects.get(id=1)
            content = cd['content']
            blog = Blog(caption=title, author=author, content=content)
            blog.save()
            for taglist in tagname.split():
                blog.tags.add(Tag.objects.get(tag_name=taglist.strip()))
                blog.save()
            id = Blog.objects.order_by('-id')[0].id
            return HttpResponseRedirect('/simpleblog/blog/%s' % id)
    else:
        form = BlogForm()
        tag = TagForm()
    return render_to_response('blog_add.html',
        {'form': form, 'tag': tag}, context_instance=RequestContext(request))


def show_weibo(request):
    weibos = Weibo.objects.order_by('-publish_time')[:5]
    return render_to_response("blog_twitter.html", {"weibos": weibos})


def add_weibo(request):
    c = {}
    c.update(csrf(request))
    if request.method == 'POST':
        massage = request.POST['twitter']
        author = Author.objects.get(id=1)
        massage = Weibo(massage=massage, author=author)
        massage.save()
        weibos = Weibo.objects.order_by('-publish_time')[:5]
        return render_to_response("blog_twitter.html",
        {"weibos": weibos},
        context_instance=RequestContext(request))
    else:
        return HttpResponse('dddd')
        # blogs = Blog.objects.order_by('-id')
        # tags = Tag.objects.all()
        # return render_to_response("blog_list.html",
        #     {"blogs": blogs, "tags": tags},
        #     context_instance=RequestContext(request))


def blog_update(request, id=""):
    id = id
    if request.method == 'POST':
        form = BlogForm(request.POST)
        tag = TagForm(request.POST)
        if form.is_valid() and tag.is_valid():
            cd = form.cleaned_data
            cdtag = tag.cleaned_data
            tagname = cdtag['tag_name']
            tagnamelist = tagname.split()
            for taglist in tagnamelist:
                Tag.objects.get_or_create(tag_name=taglist.strip())
            title = cd['caption']
            content = cd['content']
            blog = Blog.objects.get(id=id)
            if blog:
                blog.caption = title
                blog.content = content
                blog.save()
                for taglist in tagnamelist:
                    blog.tags.add(Tag.objects.get(tag_name=taglist.strip()))
                    blog.save()
                tags = blog.tags.all()
                for tagname in tags:
                    tagname = unicode(str(tagname), "utf-8")
                    if tagname not in tagnamelist:
                        notag = blog.tags.get(tag_name=tagname)
                        blog.tags.remove(notag)
            else:
                blog = Blog(caption=blog.caption, content=blog.content)
                blog.save()
            return HttpResponseRedirect('/simpleblog/blog/%s' % id)
    else:
        try:
            blog = Blog.objects.get(id=id)
        except Exception:
            raise Http404
        form = BlogForm(initial={'caption': blog.caption, 'content': blog.content}, auto_id=False)
        tags = blog.tags.all()
        if tags:
            taginit = ''
            for x in tags:
                taginit += str(x) + ' '
            tag = TagForm(initial={'tag_name': taginit})
        else:
            tag = TagForm()
    return render_to_response('blog_add.html',
        {'blog': blog, 'form': form, 'id': id, 'tag': tag},
        context_instance=RequestContext(request))

templates/simpleblog/blog_add.html
{% extends "blog_base.html" %}

{% block title %} 发布文字 {% endblock %}   
{% block otherscript %}
    <script type="text/javascript">
        $(document).ready(function(){
                $("#hint a").popover();            
            })
    </script>
{% endblock %}

{% block article %} 
{% comment %}
{% if form.errors %}
    <div class="alert alert-error">
        Please correct the error {{ form.errors|pluralize }} below.
    </div>
{% endif %}
{% endcomment %}

<form action="" method="post">
    {% csrf_token %} 
    <div class="field">
        <label for="id_caption">Title: </label>
        {% if form.caption.errors %}
        <div class="alert alert-error">
            {{ form.caption.errors }}          
        </div>
        {% endif %}
        {{ form.caption }}
    </div>
    <div class="field">        
        <label for="id_content">Content: </label>
        {% if form.content.errors %}
        <div class="alert alert-error">
            {{ form.content.errors }}
        </div>
        {% endif %}
        {{ form.content }}
    </div>
    <div class="field">
        <label for="id_tag">tags</label>
        {% if tag.tag_name.errors %}
        <div class="alert alert-error">
            {{ tag.tag_name.errors }}
        </div>
        {% endif %}
        {{ tag.tag_name }}
    </div>
    <div class="form-actions">
        <input class="btn btn-primary" type="submit" value="save and add">
        <a href="#" class="btn">Save as Draft</a>
    </div>
</form>
{% endblock %}

{% block aside %}
<div id="aside">
    <div class="alert alert-info">
    <h4>markdown syntax</h4>
</div>
<div id="hint" class="row well">
    <ul id="mark-prompt">
        <li><a class="btn btn-primary" rel="popover" href="#"  data-trigger="hover" 
            data-original-title="Strong"
            data-content="使用星号（*）和底线（_）作为标记强调字词的符号，被 * 或 _ 包围的字词会被转成用 &lsaquo;em&rsaquo; 标签包围，用两个 * 或 _ 包起来的话，则会被转成 &lsaquo;strong&rsaquo;">
            <i class="icon-bold icon-white"></i> 强调                
            </a>
        </li>
        <li><a class="btn btn-info" rel="popover" href="#" data-trigger="hover" 
            data-original-title="List" data-placement="bottom"
            data-content="Markdown 支持有序列表和无序列表。无序列表使用星号、加号或是减号作为列表标记：<br/>
            *  &emsp; Red<br/>
            *  &emsp; Green<br/>
            等同于：.....<br/>
            +  &emsp; Red<br/>
            +  &emsp; Green<br/>
            也等同于：<br/>
            -   &emsp; Red<br/>
            -   &emsp; Green<br/>
            有序列表则使用数字接着一个英文句点：<br/>
            1.  &emsp; Red<br/>
            2.  &emsp; Green">
            <i class="icon-list icon-white"></i> 列表                
            </a>
        </li>
        <li><a class="btn btn-warning" rel="popover" href="#" data-trigger="hover" 
            data-original-title="Link"
            data-content="Markdown 支持两种形式的链接语法： 行内式和参考式两种形式。<br/>
            链接文字都是用 [方括号] 来标记<br/>
            This is [an example](http://example.com/ &ldquo;Title&rdquo;) inline link.<br/> 
            参考式的链接是:<br/>
            This is [an example] [id] reference-style link.<br/>
            接着，在文件的任意处：<br/>
            [id]: http://example.com/  &ldquo;Optional Title Here&rdquo;
            ">
            <i class="icon-hand-up icon-white"></i> 链接                
            </a>
        </li>
        <li><a class="btn btn-inverse" rel="popover" href="#" data-trigger="hover" 
            data-original-title="Blockquotes"
            data-content="在每行的最前面加上 >">
            <i class="icon-comment icon-white"></i> 引用                
            </a>
        </li>
        <li><a class="btn btn-success" rel="popover" href="#" data-trigger="hover" 
            data-original-title="Picture"
            data-content="行内式的图片语法看起来像是：<br/>
            ![Alt text](/path/to/img.jpg)<br/>
            参考式的图片语法则长得像这样：<br/>
            ![Alt text][id]<br/>
            [id]: url/to/image  &ldquo;Optional title attribute&ldquo;" >
            <i class="icon-picture icon-white"></i> 图片                
            </a>
        </li>
        <li><a class="btn btn-danger" rel="popover" href="#" data-trigger="hover" 
            data-original-title="Code"
            data-content="进 4 个空格或是 1 个制表符就可以">
            <i class="icon-leaf icon-white"></i> 代码                
            </a>
        </li>
    </ul>
</div>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                Other Syntax:
            </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
            <div class="accordion-inner">
            Anim pariatur cliche...
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/simpleblog/blog_add_comments.html
{% load comments %}
{% get_comment_form for blog as blog_form %}
<div id="comment_form">
    <form class="form-horizontal" action="{% comment_form_target %}" method="post">
        <fieldset>
        {% csrf_token %}
        {{ blog_form.object_pk }}
        {{ blog_form.content_type }}
        {{ blog_form.timestamp }}
        {{ blog_form.site }}
        {{ blog_form.submit_date }}
        {{ blog_form.security_hash }}
        <div class="control-group">
            <label class="control-label" for="id_name">name: </label>
            <div class="controls">
                <input type="text" id="id_name" class="input-xlarge" name="name" placeholder="please enter name" required="required">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_email">email: </label>
            <div class="controls">
                <input class="input-xlarge" id="id_email" type="email" name="email" placeholder="please enter email" required="required">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_comment">comment: </label>
            <div class="controls">
                <textarea class="input-xlarge" id="id_comment" name="comment" placeholder="please enter comment" required="required"></textarea>
            </div>
        </div>
        <p style="display:none;"><label for="id_honeypot">如果你在该字段中输入任何内容，那么你的评论就会被视为垃圾评论。</label> <input type="text" name="honeypot" id="id_honeypot"></p>
        <div class="form-actions">
            <input class="btn btn-info" type="submit" name="submit" value="Post">
            {# <input class="btn btn-info" type="submit" name="preview" value="Preview"> #}
            <input type='hidden' name='next' value='/simpleblog/blog/{{ blog.id }}/commentshow/'/>
        </div>
        </fieldset>
    </form> 
</div>

templates/simpleblog/blog_add_weibo.html
<div class="modal hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header twitter-modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Modal header</h3>
    </div>
    <form action="" method="post">{% csrf_token %}
    <div class="modal-body twitter-modal-body">
        <textarea name="twitter" class="twitter" id="twitter" required="required"></textarea>
    </div>
    <div class="modal-footer twitter-modal-footer">
        <button class="btn"  data-dismiss="modal" aria-hidden="true">Close</button>
        <button id="send" type="submit" name="submit" aria-hidden="true" class="btn btn-primary" >Save changes</button>
    </div>
    </form>
</div>   

templates/simpleblog/blog_base.html
{% extends "base.html" %}
{% load filterlib %}

{% block extra_head %}
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
        .row{
            margin-left: 0;
        }
        #mark-prompt li{
            list-style: none outside none;
            padding: 10px 9px 3px 0;
            float: left;
        }
    </style> 
    {% block script %}
        <script type="text/javascript">
            function sendtwitter(){
                $('#myModal form').submit(function(){
                    $.ajax({
                        type: "POST",
                        data: $('#myModal form').serialize(),
                        url: "{% url addmassage %}",
                        cache: false,
                        dataType: "html",
                        success: function(html, textStatus) {
                            $('#weibo').replaceWith(html);
                            $('#myModal').modal('hide');   
                            $('#myModal form')[0].reset();                      
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            $('#comment_form form').replaceWith('Your comment was unable to be posted at this time.  We apologise for the inconvenience.');
                        }
                    });
                    return false;
                });
            }
            $(document).ready(function(){
                sendtwitter();
            })
        </script>     
    {% endblock %}
    {% block showblogscript %}{% endblock %}
    {% block otherscript %}{% endblock %}
{% endblock %}   

{% block header %}
    {% block menu %}
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">  
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <span class="sbrand">SimpleBlog</span>
                <ul class="nav">
                    <li class="active divider-vertical">           
                        <a href="{% url bloglist %}">
                            <span class="new-wrapper">
                                <i class="nav-home"></i>
                                <i class="nav-new"></i>
                            </span>
                            home
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="new-wrapper">
                                <i class="nav-me"></i>
                                <i class="nav-new"></i>
                            </span>
                            about
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="new-wrapper">
                                <i class="nav-people"></i>
                                <i class="nav-new"></i>
                            </span>               
                            contact
                        </a>
                </li>
                </ul>
                <div class="pull-right">
                    <form class="navbar-search" method="get" action="{% url searchblog %}">
                        <input type="text" class="search-query" name="search" placeholder="Search" required="required">
                    </form>
                    <ul class="nav">
                        <li class="divider-vertical"></li>
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle myset" data-toggle="dropdown">
                            <span class="new-wrapper">
                                <i class="nav-session"></i>
                                <i class="nav-new"></i>
                            </span> 
                            <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url addblog %}"><i class="icon-plus"></i> add new blog</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                        <li class="divider-vertical"></li>
                    </ul>  
                        <a class="btn btn-info btn-tweet" href="#myModal" role="button" data-toggle="modal">
                            <i class="nav-tweet">
                                <span class="hide">撰写新推文</span>
                            </i> 
                        </a>                             
                </div>                     
            </div>                
        </div>
    </div>    
    <div class="modal hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header twitter-modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Modal header</h3>
        </div>
        <form action="" method="post">{% csrf_token %}
        <div class="modal-body twitter-modal-body">
            <textarea name="twitter" class="twitter" id="twitter" required="required"></textarea>
        </div>
        <div class="modal-footer twitter-modal-footer">
            <button class="btn"  data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="send" class="btn btn-primary" type="submit" name="submit" >Save changes</button>
        </div>
        </form>
    </div>
    {% endblock %}
{% endblock %}

templates/simpleblog/blog_comments_show.html
{% load comments %}
{% load gravatar %}
{% load markup %}
<article id="cmt">
    {% get_comment_count for blog as comment_count %}    
        <h4 class="muted">{{ comment_count }} Comments</h4>
        <hr class="soften">  
    {% get_comment_list for blog as blog_com %}
    {% for comment in blog_com %}
        <div class="container-fluid none-padding">
            <div class="row-fluid">
                <div class="span1">
                <img class="gravatar" src="{% gravatar_url comment.user_email %}">
                </div>
                <div class="span10">
                <p class="muted"><small>{{ comment.user }}</small><small>{{ comment.submit_date|date:"F,j,Y" }}</small></p>      
                {{ comment.comment|markdown:'safe,codehilite' }} 
                </div>
            </div>           
        </div>
        <hr class="soften">                   
    {% endfor %}
</article>

templates/simpleblog/blog_show.html
{% extends "blog_base.html" %}
{% load comments %}
{% load gravatar %}

{% block title %} {{ blog.caption }} {% endblock %}
{% block showblogscript %}
<script type="text/javascript" charset="utf-8">
function bindPostCommentHandler() {
    $('#comment_form form input.submit-preview').remove();
    $('#comment_form form').submit(function() {
        $.ajax({
            type: "POST",
            data: $('#comment_form form').serialize(),
            url: "{% comment_form_target %}",
            cache: false,
            dataType: "html",
            success: function(html, textStatus) {
                $('#cmt').replaceWith(html);
                $('#comment_form form')[0].reset();
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                $('#comment_form form').replaceWith('Your comment was unable to be posted at this time.  We apologise for the inconvenience.');
            }
        });
        return false;
    });
}
 
$(document).ready(function() {
    bindPostCommentHandler();
});
</script>  
{% endblock %} 


{% block article %} 
<article class="content-main">
    {% block article_title %}
        <h2>{{ blog.caption }}</h2>
    {% endblock %}
    <p class="muted">
        <i class="icon-user"></i><small> {{ blog.author }}</small>  
        <i class="icon-time"></i><small> {{ blog.publish_time }}</small>
    </p>
    <hr class="soften">
    <section>
        <div class="blog-content">
            {% load markup %}
            {% block article_content %}
                {{ blog.content|markdown:"safe,codehilite" }}
            {% endblock %} 
        </div>
    </section>
    <section>
        <div class="row-fluid post-info">
        <div class="span3">
            <p>  
                <i class="icon-tag"></i>
                {% for tag in blog.tags.all %}
                     <small class="muted"> {{ tag }} </small>
                {% endfor %}
            </p>  
        </div>
        <div class="span2 offset7">
            <a href="{% url delblog blog.id %}" title="delete"><i class="icon-trash"></i></a>
            <a href="{% url updateblog blog.id %}" title="edit"><i class="icon-edit"></i></a>
            {% get_comment_count for blog as comment_count %}
            <a href="#cmt" title="comment"><i class=" icon-comment"></i>{{ comment_count }}</a>
        </div>
    </div>
    <hr class="soften">
    </section>    
</article>

{% endblock %}

{% block comments %}    
<article id="cmt">
    {% get_comment_count for blog as comment_count %}    
        <h4 class="muted comtop">{{ comment_count }} Comments</h4>
        <hr class="soften">  
    {% get_comment_list for blog as blog_com %}
    {% for comment in blog_com %}
        <div class="container-fluid none-padding">
            <div class="row-fluid">
                <div class="span1">
                <img class="gravatar" src="{% gravatar_url comment.user_email %}">
                </div>
                <div class="span10">
                <p class="muted"><small>{{ comment.user }}</small><small>{{ comment.submit_date|date:"F,j,Y" }}</small></p>      
                {{ comment.comment|markdown:'safe,codehilite' }} 
                </div>
            </div>           
        </div>
        <hr class="soften">                   
    {% endfor %}
</article>

<article >     
    {% get_comment_form for blog as blog_form %}  
        <div id="comment_form">
            <h4 class="muted comtop">New Comments</h4>
            <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                <fieldset>
                {% csrf_token %}
                {{ blog_form.object_pk }}
                {{ blog_form.content_type }}
                {{ blog_form.timestamp }}
                {{ blog_form.site }}
                {{ blog_form.submit_date }}
                {{ blog_form.security_hash }}
                <div class="control-group">
                    <label class="control-label" for="id_name">name: </label>
                    <div class="controls">
                        <input type="text" id="id_name" class="input-xlarge" name="name" placeholder="please enter name" required="required">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_email">email: </label>
                    <div class="controls">
                        <input class="input-xlarge" id="id_email" type="email" name="email" placeholder="please enter email" required="required">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_comment">comment: </label>
                    <div class="controls">
                        <textarea class="input-xlarge comment" id="id_comment" name="comment" placeholder="please enter comment" required="required"></textarea>
                    </div>
                </div>
                <p style="display:none;"><label for="id_honeypot">如果你在该字段中输入任何内容，那么你的评论就会被视为垃圾评论。</label> <input type="text" name="honeypot" id="id_honeypot"></p>
                <div class="form-actions">
                    <input class="btn btn-info" type="submit" name="submit" value="Post">
                    {# <input class="btn btn-info" type="submit" name="preview" value="Preview"> #}
                    <input type='hidden' name='next' value='{% url showcomment blog.id %}'/>
                </div>
                </fieldset>
            </form> 
        </div>
</article>
{% endblock %}

templates/simpleblog/blog_twitter.html
{% block twitter %}
    <div id="weibo" class="well">
        {% for weibo in weibos %}
            <p class="text-info">{{ weibo }}</p>                
            <p class="text-success"><small>{{ weibo.publish_time }}</small></p>
            <hr class="soften">
        {% endfor %}
    </div>
{% endblock %}